# Site settings
title: Gabriele Castellani's blog
email: gabrielecastellani at hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gabrielecastellani.it" # the base hostname & protocol for your site

disqus_short_name: gabrielecastellanisblog
disqus_show_comment_count: true

#
# Jekyll Settings
#
markdown: redcarpet
permalink: /archive/:year/:month/:day/:title/
paginate: 10
paginate_path: "page/:num"
category_dir: categories

highlighter: pygments

# Github repositories
github_user: gabrielecastellani
github_repo_url: https://github.com/GabrieleCastellani/gabrielecastellani.github.io

twitter_username: gabrielec
github_username:  gabrielecastellani

gems:
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
